### ISSUE TITLE
Don't visible on 125% Scale

### ISSUE THREAD

**Issue by BaalEvan** [BaalTech/Floating-Clock#2]
First of all, thank you very much for taking the time to create something like that; it was the missing piece for a perfect Windows 10 experience for me.

Sadly, it doesn't seem fully functionnal on my Asus Zenbook. The program does launch but nothing is showing on my desktop. I know the program is functional because when I press the keyboard shortcut I loose focus on y active windows, and the charm clock shows up on my exposé view. (http://imgur.com/2gxxbBA)

Unfortunately no black box, it seems like it's transparent or something. Do you have any idea what's going on ?

Thanks a lot !

Edit : Found some sort of clue. It has something to do with display scaling. It works fine at a 100% scale but is wonky at 125% (Preferable for my eyes on a 13 inch Full HD display). Don't know if this helps

**Comment by tOverney** [comment]
Yes :(
I have the same issue but my zoom level is 225%
