### ISSUE TITLE
Can you update this app?

### ISSUE THREAD

**Issue by motfis** [BaalTech/Floating-Clock#7]

**Comment by BaalEvan** [comment]
Yeah, i can but it's working on my PC, do you need anything special?

**Comment by motfis** [comment]
glad you are still active. last update was in 2015.
Nothing special. It just does not work on 2 of my PC. Win 10 build 1909.

If you can maybe it is good to automatic enable this clock when swiping right (notification), as in the past we swipe charm bar :) but ghis is low priority.

**Comment by BaalEvan** [comment]
not sure if its possible ;/ can you check if you have display scale over 100%?

**Comment by motfis** [comment]
(un)fortunatelly, you are right. I have display scaling of 150%.
I tried display scaling 100%, and it worked. But I cannot use my PC with display scaling 100%, everything is very tiny.
Is there possibility to fix this app for display scaling not 100%?

**Comment by motfis** [comment]
1 "hint", if I use display scaling 100%, then run the app, it works. After that, if I change display scaling to other, it still works.
If I run directly with scaling not 100%, it does not work.

**Comment by BaalEvan** [comment]
I uploaded new release, should be ok now

**Comment by motfis** [comment]
Thank you very much!!
It works very well now :)
